name: Build and Test (No Push)

on:
  push:
    branches: [ "main" ]

env:
    AWS_REGION: ap-south-1                                          # Replace with your AWS region
    ECR_REPOSITORY: 782857344754.dkr.ecr.ap-south-1.amazonaws.com/docker_repo            # ECR Repo name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SCERET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Note: "Login to Docker Hub" step is REMOVED since we aren't pushing
      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Load Image
        uses: docker/build-push-action@v4
        with:
          context: .                    # Context is root
          file: ./docker_files/Dockerfile     # File is in subfolder
          push: true                   # <--- STOP the push to Docker Hub
          load: true                    # <--- EXPORT the image to local Docker daemon
          # We combine the Registry URL + Repo Name + Tag
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/docker_repo:${{ steps.vars.outputs.sha_short }}


